name: CD Localhost

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed
    branches:
      - main

jobs:
  despliegue-local:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: [self-hosted, Windows, X64]

    steps:
      - name: Descargar codigo actualizado
        uses: actions/checkout@v4

      - name: Ejecutar script de despliegue local
        shell: powershell
        env:
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_NAME: ${{ secrets.DB_NAME }}
        run: .\scripts\deploy-local.ps1